### PR TITLE
docs(redux): remove redux docs

### PR DESCRIPTION
**Pull request by tanner-reits**
Removes the docs for Redux and Stencil Redux. Updates our redirects to point these URLs to the archived Stencil Redux repo

### CODE REVIEW

**Comment by tanner-reits** [comment]
Not sure why CI is falling over since I didn't change dependencies at all. I ran the check locally and everything passed there

**Review by alicewriteswrongs — APPROVED** [review]
lgtm!

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
LGTM - can you rebase off of main and rm these from the `versioned_docs/version-v3.1/` dir please?

**Comment by tanner-reits** [comment]
All is well now

**Review by alicewriteswrongs — APPROVED** [review]

**Review by rwaskiewicz — APPROVED** [review]

**Pull request merged**
