### PR TITLE
Use auto binding arrow function syntax

### PR DESCRIPTION
**Pull request by danawoodman**
Just a suggestion, but encouraging people to use the cleaner auto-binding arrow function syntax instead results in cleaner code (IMO). Feel free to accept/reject as you see fit!

Also made it consistently use `e` for the event param

### CODE REVIEW

**Comment by manucorporat** [comment]
I would rather explain this better in a "Best practices" guide, otherwise people might misunderstand they can use the method directly without `bind()` and that could break their apps.

**Comment by danawoodman** [comment]
True, but previous examples use this syntax so if so those should also be changed. I did this in part to keep the examples more consistent

**Comment by adamdbradley** [comment]
Sorry we were unable to merge this, but looks like too many conflicts. Thanks

**Comment by danawoodman** [comment]
Lol, yeah that’s because you guys waited 5 months to merge it! 😂

**Pull request closed without merging**
