### PR TITLE
chore(deps): update ionic-docs/preset-classic, docusaurus to v3

### PR DESCRIPTION
**Pull request by jaredcbaum**
This PR updates the `@ionic-docs/preset-classic` dependency.

This includes updates to Docusaurus v3 (which includes MDX v3)

Takes care of #1263, #1294 and makes #1285 obsolete

### CODE REVIEW

**Comment by jaredcbaum** [comment]
@alicewriteswrongs @rwaskiewicz looks like there was a change to how links are handled in Docusaurus v3 which is causing the build to fail. Do you want me to make decisions about how to link between documents or would you like to handle that on your side?

Here's some related documentation: https://docusaurus.io/docs/markdown-features/links

**Comment by rwaskiewicz** [comment]
@jaredcbaum 


RE: Links - this appears to be related to a possible(?) bug where links that have a newline in their name (between the sq brackets) don't seem to be parsed properly. I have a commit locally that fixes most of these, I'll push it to this branch after today's Stencil release

**Comment by rwaskiewicz** [comment]
@jaredcbaum I pushed https://github.com/ionic-team/stencil-site/pull/1290/commits/7f8e8a2fb16fdade10a7a19273cf5315e2f85b7a, which has most of the fixes - can you do me a favor and rebase this when you get a chance and LMK? I'll update the last few broken links in the newly created v4.9 section (that's not in this branch ATM).

**Comment by jaredcbaum** [comment]
@rwaskiewicz rebased

**Comment by rwaskiewicz** [comment]
@jaredcbaum Links are all fixed, build + deploy is passing now 🎉 

LMK when you'd like us to take a look and review!

**Review by rwaskiewicz — APPROVED** [review]

**Comment by rwaskiewicz** [comment]
@jaredcbaum could you do me a favor an rebase this one more time? Other than another Stencil team member taking a look, is there anything else blocking this from landing? I can get someone to take a look today

**Comment by jaredcbaum** [comment]
No, this is ready to land. I can rebase

**Review by alicewriteswrongs — APPROVED** [review]
all looks good to me!

**Pull request merged**
