### PR TITLE
Add service worker examples

### PR DESCRIPTION
**Pull request by simonhaenisch**
After discussion with @adamdbradley, instead of supplying custom service workers with certain starters (using Workbox's `injectManifest` mode), we will rely on the `generateSW` mode by default. The docs will be updated to include examples for advanced techniques (e. g. handling push, showing a reload toast).

The goal is to provide a good default service worker, and to prevent developers who lack experience with service workers from having to deal with service worker issues just because they used a certain starter for their project (e. g. https://github.com/ionic-team/stencil/issues/1102).

### CODE REVIEW

**Comment by manucorporat** [comment]
I would love to merge this changes! are you still working on this? cc @simonhaenisch

**Comment by simonhaenisch** [comment]
@manucorporat I was going to add one more example but I don't have time to finish that right now, so I might just open another PR later on. I'll solve the conflicts now.

**Comment by simonhaenisch** [comment]
@manucorporat I actually remember now, I wanted to finish the section about handling push events. At the moment there is only a code example there but no description yet... I'll open a PR probably after Christmas.

BTW is it intended that the service worker is disabled now for the docs site?

**Comment by simonhaenisch** [comment]
Just found this: https://twitter.com/davidbrunelle/status/1073394572980453376

Might be another good example to add. I’ll have some free time tomorrow, so I’ll look at finishing this.

**Comment by simonhaenisch** [comment]
@manucorporat I finished this now, and it's ready to be merged. I made a preview available at https://stencil-site-f2ow9ximf.now.sh/docs/service-workers.

One more thing to discuss though is what to do with the service worker for this site?

You disabled the service worker (91536ac327dab6f112031f07f6d2a1cba025bc3a) a while ago. I'm not sure whether the code you introduced to unregister all current service workers (eb004cce2161e7faf0c884938ad1ab7e192064e7) works though, because I and others still had an old site served from an active service worker last week (see https://github.com/ionic-team/stencil/issues/1196#issuecomment-448251194).

After my last discussion with @adamdbradley, the decision back then was to go with the default strategy: a waiting service worker won't take over until the site is re-opened, ensuring a consistent experience for the user. That should be fine because it's unlikely that people would keep a tab with the Stencil site open for very long (i. e. weeks), and doc updates are not super critical?

I opened PRs to do the same for https://github.com/ionic-team/ionic-stencil-conference-app/pull/172 and https://github.com/ionic-team/ionic-pwa-toolkit/pull/96: remove the custom service worker and just use the default Workbox generated one instead. This should be a good minimal boilerplate setup for most use cases, and this doc update will help people dive in deeper if they want to implement something like a reload toast.

**Comment by simonhaenisch** [comment]
Just wondering, should I add an example for how to add a cache strategy for certain files?

E. g. for an Ionic app, this would serve all the Ionicon `.svg`s from cache first:

```js
self.workbox.routing.registerRoute(
  /build\/app\/svg\/.+\.svg/i,
  self.workbox.strategies.cacheFirst(),
);
```

**Pull request merged**
