### PR TITLE
docs(config): add docs for new `experimentalSlotFixes` config value

### PR DESCRIPTION
**Pull request by alicewriteswrongs**
A small documentation PR just adding a bit of explanation of what this field is for.

### CODE REVIEW

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
I think for this field, we're going to want to be pretty descriptive about what this field is, how it's being used, and what folks should expect if they enable it now (and in the future). At the moment, this is going to be one of (if not the) primary source of information for this flag. With that in mind, I think we'd want something to the effect of:

> A flag introduced in Stencil to enable new slot-related fixes to the Stencil runtime.
> When enabled, this flag will enable the following flags:
> - [list}
>
> This flag also contains fixes for the following issues that do not have a configuration flag associated with them:
> - [List of issues]
>
> Fixes to the runtime that are a part of this flag will be added over the course of Stencil v4, with the intent of making these the default behavior in Stencil v5.
>  New fixes added to this flag are not subject to Stencil's [semantic versioning policy](../reference/versioning).


The "This flag also contains fixes for the following issues" part would have to come later though, since we don't have any ATM.


But that's all just an example of what I'm thinking of in terms of things we should tell folks about. Thoughts?

**Comment by tanner-reits** [comment]
Agree this should be pretty descriptive. Might be good to also add a sentence like "This option will override any values specified in the `extras` config section for slot related fixes/polyfills". This way, users understand that this takes precedence.

**Review by tanner-reits — COMMENTED** [review]
Agree this should be pretty descriptive. Might be good to also add a sentence like "This option will override any values specified in the `extras` config section for slot related fixes/polyfills". This way, users understand that this takes precedence.

**Comment by alicewriteswrongs** [comment]
@rwaskiewicz makes sense, I just updated the copy in line with your suggestions

**Review by rwaskiewicz — APPROVED** [review]

**Review by tanner-reits — APPROVED** [review]

**Pull request merged**
