### PR TITLE
docs(3.3): fix document typo

### PR DESCRIPTION
**Pull request by boradakash**

### CODE REVIEW

**Review by rwaskiewicz — COMMENTED** [review]
Thanks! Could you do me a favor and update our 'next' documentation as well? https://github.com/ionic-team/stencil-site/blob/969bafe55a104649c557c10aba630b69af4ed7cd/docs/components/api.md?plain=1#L57

**Comment by boradakash** [comment]
Sure, I just created PR for it.
https://github.com/ionic-team/stencil-site/pull/1132

**Comment by boradakash** [comment]
Also updated it for v3.2

**Review by rwaskiewicz — APPROVED** [review]
Thanks!

**Pull request merged**
