### PR TITLE
Refactor/abstract preset v2

### PR DESCRIPTION
**Pull request by jaredcbaum**
This PR:
- swaps out the `@ionic-internal/preset-classic` package for `@ionic-docs/preset-classic` package
- refactors docusaurus.config.js to work with new theme
- removes unnecessary packages from `package.json` that have been abstracted to the preset
- removes styles that have been abstracted to preset
- misc formatting changes to stay consistent with ionic's prettier syntax

### CODE REVIEW

**Comment by alicewriteswrongs** [comment]
One small thing I noticed is in the new product drop-down UI item there's a Discord link which links to ionic.link/discord:

Screenshot 2023-11-30 at 11 05 23 AM


we have a redirect from chat.stenciljs.com to the discord which is what we use currently in the 'Community' accordian thingy in the site sidebar

Screenshot 2023-11-30 at 11 04 55 AM

could we possibly get that link into the discord icon link in the top-left dropdown too? I'm not sure if the preset allows that to be configured, but it's nice to have the redirect in case it needs to point somewhere else in the future

**Comment by alicewriteswrongs** [comment]
Otherwise looks good! I sort of miss the emojis in the admonitions but I can live with that 😄

**Comment by jaredcbaum** [comment]
Ok, those discord links are updated!

**Review by alicewriteswrongs — APPROVED** [review]
looks good to me!

**Pull request merged**
