### PR TITLE
chore: Docusaurus 3.1, latest preset

### PR DESCRIPTION
**Pull request by jaredcbaum**
Updates docusuarus preset to latest and Docusaurus dependencies to 3.1.0.

Closes #1311

### CODE REVIEW

**Comment by jaredcbaum** [comment]
Docusaurus also recommends adding a config option `onBrokenAnchors` with a value of `throw`.

https://docusaurus.io/blog/releases/3.1#broken-anchors-checker

**Comment by rwaskiewicz** [comment]
@jaredcbaum out of curiosity, how did you go about updating Docusaurus? It seems that this morning, Renovate tried to do the same and failed, requiring @alicewriteswrongs to [manually intervene](https://github.com/ionic-team/stencil-site/pull/1311#issuecomment-1883271630) (comment) on this PR: https://github.com/ionic-team/stencil-site/pull/1311. However, the changes in that linked PR are much smaller in terms of lines of code than this one 🤔

**Comment by jaredcbaum** [comment]
@rwaskiewicz In release 1.1 of the `@ionic-docs/preset-classic` package, I updated all the Docusaurus dependencies to 3.1. This should mean all Docusaurus related packages are running the same version after the updates to the docusaurus deps local to this repo.

**Review by rwaskiewicz — APPROVED** [review]

**Comment by alicewriteswrongs** [comment]
Looks fine to me, we can close #1311 in favor of this - that does raise the question of if we need to do this specific manual intervention and wait on a bump of `@ionic-docs/preset-classic` should be perhaps tell Renovate not to try to upgrade Docusaurus packages?

**Review by alicewriteswrongs — APPROVED** [review]

**Comment by rwaskiewicz** [comment]
@alicewriteswrongs 

> that does raise the question of if we need to do this specific manual intervention and wait on a bump of @ionic-docs/preset-classic should be perhaps tell Renovate not to try to upgrade Docusaurus packages?

Perhaps, I'm not super well versed in the dependency needs of the preset here. I'll create a conversation in Slack with the Web team and we can figure things out there.

**Pull request merged**
